#source("1 - Baseline (same as 9 in models).R")
#source("2 - Diagnostic Virtual Ward.R")
#source("2b - Diagnostic Virtual Ward.R")
#source("3 - Infinite Wards (aka what do we need).R")
#source("4 - reduce A&E admissions.R")
#source("4b - reduce A&E admissions.R")
#source("5 - Hotel for delayed discharges.R")
#source("6 - prospective cancellations.R")
#source("6b - prospective cancellations.R")
#source("7 - Periop unit.R")
source("7b - Periop unit.R")
source("7c - Periop unit.R")
#source("7d - Periop unit.R")
#source("7e - Periop unit.R")